// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package faq

type Faq struct {
	ID        int32  `json:"id"`
	Question  string `json:"question"`
	Answer    string `json:"answer"`
	IsPremium bool   `json:"is_premium"`
}
