# Refinando o Air para uma saída de TDD ultra-limpa...

root = "."
tmp_dir = "tmp"

[build]

# --format testname: Mostra o nome de cada teste de forma limpa

# --format-hide-empty-pkg: Esconde pacotes que não têm testes (ex: users/db)

# --hide-summary all: Remove a repetição do erro no final do log

cmd = "gotestsum --format testname --format-hide-empty-pkg --hide-summary skipped,failed,errors,output -- ./users/..."
full_bin = "true"
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "vendor", "db"]
delay = 500

[log]
time = false
main_only = true

[screen]
clear_on_rebuild = true