# STREAMING_CHUNK: Finalizing clean output configuration...

root = "."
tmp_dir = "tmp"

[build]

# Usamos --format pkgname-and-test-fails para ver apenas o essencial: pacote e tempo.

cmd = "gotestsum --format pkgname-and-test-fails -- ./users/..."
full_bin = "true"
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "vendor", "db"]
delay = 500

[log]
time = false
main_only = true

[screen]
clear_on_rebuild = true