// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createFAQ = `-- name: CreateFAQ :one
INSERT INTO faqs (question, answer, is_premium)
VALUES ($1, $2, $3)
RETURNING id, question, answer, is_premium
`

type CreateFAQParams struct {
	Question  string `json:"question"`
	Answer    string `json:"answer"`
	IsPremium bool   `json:"is_premium"`
}

func (q *Queries) CreateFAQ(ctx context.Context, arg CreateFAQParams) (Faq, error) {
	row := q.db.QueryRowContext(ctx, createFAQ, arg.Question, arg.Answer, arg.IsPremium)
	var i Faq
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.IsPremium,
	)
	return i, err
}

const deleteFAQ = `-- name: DeleteFAQ :exec
DELETE FROM faqs
WHERE id = $1
`

func (q *Queries) DeleteFAQ(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFAQ, id)
	return err
}

const listFAQs = `-- name: ListFAQs :many
SELECT id, question, answer, is_premium
FROM faqs
ORDER BY id
`

func (q *Queries) ListFAQs(ctx context.Context) ([]Faq, error) {
	rows, err := q.db.QueryContext(ctx, listFAQs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Faq
	for rows.Next() {
		var i Faq
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Answer,
			&i.IsPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFAQ = `-- name: UpdateFAQ :one
UPDATE faqs
SET question = $2,
  answer = $3,
  is_premium = $4
WHERE id = $1
RETURNING id, question, answer, is_premium
`

type UpdateFAQParams struct {
	ID        int32  `json:"id"`
	Question  string `json:"question"`
	Answer    string `json:"answer"`
	IsPremium bool   `json:"is_premium"`
}

func (q *Queries) UpdateFAQ(ctx context.Context, arg UpdateFAQParams) (Faq, error) {
	row := q.db.QueryRowContext(ctx, updateFAQ,
		arg.ID,
		arg.Question,
		arg.Answer,
		arg.IsPremium,
	)
	var i Faq
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.IsPremium,
	)
	return i, err
}
